// Legacy styles - these components are no longer used by the main MissionSettings
// This file exists to prevent import errors from legacy sub-components
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  formGroup: { padding: 10 },
  sectionTitle: { fontSize: 14, fontWeight: 'bold' },
  subsectionTitle: { fontSize: 12, fontWeight: '600' },
  input: { borderWidth: 1, borderColor: '#ccc', padding: 6, borderRadius: 4, height: 32 },
  inputRow: { flexDirection: 'row', gap: 8, marginBottom: 8 },
  inputGroup: { flex: 1 },
  labelSmall: { fontSize: 11, color: '#555', marginBottom: 2 },
  numberInput: { borderWidth: 1, borderColor: '#ccc', padding: 6, borderRadius: 4, height: 32 },
  switchContainer: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  fuelDistribution: { padding: 10 },
  modernSliderContainer: { gap: 8 },
  textArea: { borderWidth: 1, borderColor: '#ccc', padding: 8, height: 80, borderRadius: 4 },
  cargoList: { marginTop: 10 },
  tableContainer: { borderWidth: 1, borderColor: '#007bff' },
  tableRow: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#007bff' },
  tableCell: { flex: 1, padding: 8, borderRightWidth: 1, borderRightColor: '#007bff', alignItems: 'center' },
  tableHeaderText: { fontWeight: 'bold', fontSize: 12 },
  tableCellText: { fontSize: 12 },
  addButton: { backgroundColor: '#007bff', padding: 8, borderRadius: 4, alignItems: 'center' },
  addButtonText: { color: '#fff', fontWeight: 'bold' },
  removeButtonSmall: { width: 24, height: 24, borderRadius: 12, backgroundColor: '#ff3b30', alignItems: 'center', justifyContent: 'center' },
  removeButtonText: { color: '#fff', fontWeight: 'bold' },
  label: { fontSize: 12, color: '#333', marginBottom: 4 },
  dateContainer: { marginBottom: 10 },
  dateRow: { flexDirection: 'row', alignItems: 'center' },
  dateGroup: { flexDirection: 'row', alignItems: 'center' },
  arrowButton: { padding: 8 },
  arrowText: { fontSize: 14, color: '#007bff' },
  dateValue: { fontSize: 14, minWidth: 30, textAlign: 'center' },
  dateSeparator: { marginHorizontal: 4 },
  inputHalf: { flex: 1 },
});
