import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  deckContainer: {
    flex: 2,
  },
  deck: {
    flex: 1,
    backgroundColor: '#fff',
    // borderRadius: 8,
    position: 'relative',
    overflow: 'hidden',
  },
  cargoItem: {
    position: 'absolute',
    backgroundColor: '#4a90e2',
    borderWidth: 1,
    borderColor: '#4a90e2',
    borderRadius: 2,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    zIndex: 1,
  },
  selectedItem: {
    borderWidth: 1,
    borderColor: '#ff6b6b',
    zIndex: 2,
  },
  draggingItem: {
    opacity: 0.8,
    shadowOpacity: 0.5,
    shadowRadius: 10,
    zIndex: 999,
  },
  itemName: {
    color: '#fff',
    fontWeight: '500',
    fontSize: 10,
    textAlign: 'center',
  },
  itemContentContainer: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 4,
  },
  removeButton: {
    position: 'absolute',
    top: -2,
    right: -2,
    backgroundColor: '#ff6b6b',
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1500,
    textAlign: 'center',
  },
  removeButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
    paddingBottom: 0,
    paddingLeft: 0,
  },
  coordLabel: {
    position: 'absolute',
    fontSize: 10,
    backgroundColor: 'rgba(255,255,255,0.7)',
    color: '#000',
    padding: 1,
    zIndex: 1000,
  },
  editButton: {
    position: 'absolute',
    top: -4,
    left: -4,
    backgroundColor: '#f5a623',
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1500,
    textAlign: 'center',
  },
  fsEditPopover: {
    position: 'absolute',
    top: -78,
    right: -35,
    backgroundColor: 'white',
    borderRadius: 6,
    padding: 8,
    alignItems: 'flex-start',
    rowGap: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 6,
    zIndex: 2000,
    width: 110,
  },
  fsAndDockContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  fsEditLabel: {
    fontWeight: 'bold',
    fontSize: 12,
    marginRight: 4,
    color: '#333',
  },
  fsEditInput: {
    width: '60%',
    height: 28,
    borderColor: '#aaa',
    borderWidth: 1,
    borderRadius: 4,
    paddingHorizontal: 4,
    fontSize: 12,
    marginRight: 6,
    color: '#333',
    backgroundColor: '#f7f7f7',
  },
  fsOkCancelContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  fsEditConfirm: {
    backgroundColor: '#4a90e2',
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginRight: 4,
  },
  fsEditConfirmText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 10,
  },
  fsEditCancel: {
    backgroundColor: '#eee',
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  fsEditCancelText: {
    color: '#333',
    fontSize: 10,
  },
  dockSelectorContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 6,
    marginBottom: 4,
    width: '100%',
    gap: 4,
  },
  dockOption: {
    flex: 1,
    paddingVertical: 4,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: 'transparent',
    boxShadow: '0 0 2px 1px #aaa5',
    backgroundColor: '#f7f7f7',
    alignItems: 'center',
  },
  dockOptionSelected: {
    backgroundColor: '#4a90e2',
    borderColor: '#4a90e2',
  },
  dockOptionText: {
    fontSize: 11,
    color: '#333',
    fontWeight: '500',
  },
  dockOptionTextSelected: {
    color: 'white',
    fontWeight: 'bold',
  },
  dockOptionSingle: {
    // width: 36,
    backgroundColor: '#555',
    borderColor: '#555',
    height: 28,
    justifyContent: 'center',
    alignItems: 'center',
    // marginLeft: 8,
  },
});
