import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  stageContainer: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  stageItems: {
    flex: 1,
    padding: 10,
    position: 'relative',
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignContent: 'flex-start',
  },
  cargoItem: {
    backgroundColor: '#4a90e2',
    margin: 5,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    zIndex: 1,
  },
  selectedItem: {
    borderWidth: 2,
    borderColor: '#ff6b6b',
    zIndex: 2,
  },
  draggingItem: {
    opacity: 0.8,
    shadowOpacity: 0.5,
    shadowRadius: 10,
    borderWidth: 2,
    borderColor: 'yellow',
    backgroundColor: '#5da0f2',
    zIndex: 9999,
  },
  itemContentContainer: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 4,
  },
  itemName: {
    color: '#fff',
    fontWeight: '500',
    fontSize: 14,
    textAlign: 'center',
  },
  removeButton: {
    position: 'absolute',
    top: 2,
    right: 2,
    backgroundColor: '#ff6b6b',
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 3,
  },
  removeButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
  },
  emptyMessage: {
    textAlign: 'center',
    color: '#888',
    alignSelf: 'center',
    marginTop: 20,
  },
});
